### ISSUE TITLE
Are local files supported?

### ISSUE THREAD

**Issue by pheyvaer** [rubensworks/GraphQL-LD-Comunica.js#4]
I get the following error when referring to a local file, using `type: "file"`:
```
Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-file.json#mediatorRdfDereference mediated over all rejecting actors:
Error: This actor can only handle URLs that start with 'http' or 'https'.
```
It works when using a URL that points to a file.

**Comment by rubensworks** [comment]
No, the default comunica instance does not support querying from local files. So you'll have to create your own config and implement `IQueryEngine` like in [`QueryEngineComunica`](https://github.com/rubensworks/GraphQL-LD-Comunica.js/blob/master/lib/QueryEngineComunica.ts).
